import { Capacitor } from '@capacitor/core';
import { appConfig } from '@/config.ts';
import { LATEST_DB_VERSION, MIGRATIONS } from './migrations.ts';

/** Minimal executor abstraction: native SQLite on device, in-memory fallback on web. */
export interface DbExecutor {
  execute(sql: string, params?: unknown[]): Promise<void>;
  query<T>(sql: string, params?: unknown[]): Promise<T[]>;
  getVersion(): Promise<number>;
  setVersion(v: number): Promise<void>;
}

// ---------------------------------------------------------------------------
// Memory Executor — lightweight in-memory SQL handler for web / tests.
// Handles the specific SQL patterns generated by our repositories.
// ---------------------------------------------------------------------------

class MemoryExecutor implements DbExecutor {
  private tables = new Map<string, Record<string, unknown>[]>();
  private version = 0;

  private getTable(name: string): Record<string, unknown>[] {
    if (!this.tables.has(name)) this.tables.set(name, []);
    return this.tables.get(name)!;
  }

  async execute(sql: string, params: unknown[] = []): Promise<void> {
    const trimmed = sql.trim();

    // PRAGMA user_version = N
    const pragmaSet = trimmed.match(/^PRAGMA\s+user_version\s*=\s*(\d+)$/i);
    if (pragmaSet) {
      this.version = Number(pragmaSet[1]);
      return;
    }

    // CREATE TABLE / INDEX — no-op (schema is implicit)
    if (/^CREATE\s/i.test(trimmed)) return;

    // INSERT OR REPLACE INTO table (cols) VALUES (vals)
    const upsertMatch = trimmed.match(
      /^INSERT\s+OR\s+REPLACE\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)/i,
    );
    if (upsertMatch) {
      const table = upsertMatch[1].toLowerCase();
      const cols = upsertMatch[2].split(',').map((c) => c.trim());
      const row: Record<string, unknown> = {};
      cols.forEach((col, i) => {
        row[col] = params[i] ?? null;
      });
      const rows = this.getTable(table);
      const pkCol = cols[0];
      const pkVal = row[pkCol];
      const idx = rows.findIndex((r) => r[pkCol] === pkVal);
      if (idx >= 0) {
        rows[idx] = row;
      } else {
        rows.push(row);
      }
      return;
    }

    // INSERT INTO table (cols) VALUES (vals)
    const insertMatch = trimmed.match(
      /^INSERT\s+INTO\s+(\w+)\s*\(([^)]+)\)\s*VALUES\s*\(([^)]+)\)/i,
    );
    if (insertMatch) {
      const table = insertMatch[1].toLowerCase();
      const cols = insertMatch[2].split(',').map((c) => c.trim());
      const row: Record<string, unknown> = {};
      cols.forEach((col, i) => {
        row[col] = params[i] ?? null;
      });
      this.getTable(table).push(row);
      return;
    }

    // UPDATE table SET col1 = val1, col2 = val2 WHERE id = ?
    const updateMatch = trimmed.match(
      /^UPDATE\s+(\w+)\s+SET\s+(.+?)\s+WHERE\s+(\w+)\s*=\s*\?$/i,
    );
    if (updateMatch) {
      const table = updateMatch[1].toLowerCase();
      const setClause = updateMatch[2];
      const whereCol = updateMatch[3].toLowerCase();
      const rows = this.getTable(table);
      const whereVal = params[params.length - 1];

      const assignments = setClause.split(',').map((a) => a.trim());

      for (const row of rows) {
        if (String(row[whereCol]) === String(whereVal)) {
          let setParamIdx = 0;
          for (const assignment of assignments) {
            const eqIdx = assignment.indexOf('=');
            const col = assignment.substring(0, eqIdx).trim().toLowerCase();
            const val = assignment.substring(eqIdx + 1).trim();

            if (val === '?') {
              row[col] = params[setParamIdx++];
            } else if (val.toUpperCase() === 'NULL') {
              row[col] = null;
            } else if (/^-?\d+$/.test(val)) {
              row[col] = Number(val);
            } else {
              row[col] = val.replace(/^['"]|['"]$/g, '');
            }
          }
        }
      }
      return;
    }

    // DELETE FROM table WHERE col = ?
    const deleteMatch = trimmed.match(
      /^DELETE\s+FROM\s+(\w+)\s+WHERE\s+(\w+)\s*=\s*\?$/i,
    );
    if (deleteMatch) {
      const table = deleteMatch[1].toLowerCase();
      const col = deleteMatch[2].toLowerCase();
      const val = params[0];
      const rows = this.getTable(table);
      this.tables.set(
        table,
        rows.filter((r) => String(r[col]) !== String(val)),
      );
      return;
    }
  }

  async query<T>(sql: string, params: unknown[] = []): Promise<T[]> {
    const trimmed = sql.trim();

    // PRAGMA user_version
    if (/^PRAGMA\s+user_version$/i.test(trimmed)) {
      return [{ user_version: this.version }] as T[];
    }

    // SELECT COUNT(*) as cnt FROM table WHERE …
    const countMatch = trimmed.match(
      /^SELECT\s+COUNT\(\*\)\s+(?:as\s+\w+\s+)?FROM\s+(\w+)(?:\s+WHERE\s+(.+?))?(?:\s*$)/i,
    );
    if (countMatch) {
      const table = countMatch[1].toLowerCase();
      const whereClause = countMatch[2];
      let rows = this.getTable(table);
      if (whereClause) {
        rows = this.applyWhere(rows, whereClause, params);
      }
      return [{ cnt: rows.length }] as T[];
    }

    // SELECT value FROM app_settings WHERE key = ?
    const settingMatch = trimmed.match(
      /^SELECT\s+value\s+FROM\s+app_settings\s+WHERE\s+key\s*=\s*\?$/i,
    );
    if (settingMatch) {
      const key = params[0] as string;
      const rows = this.getTable('app_settings');
      const row = rows.find((r) => r.key === key);
      return row ? [{ value: row.value }] as T[] : [];
    }

    // SELECT * FROM table [WHERE …] [ORDER BY col ASC/DESC]
    const selectMatch = trimmed.match(
      /^SELECT\s+\*\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+?))?(?:\s+ORDER\s+BY\s+(\w+)\s+(ASC|DESC))?$/i,
    );
    if (selectMatch) {
      const table = selectMatch[1].toLowerCase();
      const whereClause = selectMatch[2];
      const orderCol = selectMatch[3];
      const orderDir = (selectMatch[4] ?? 'ASC').toUpperCase();

      let rows = [...this.getTable(table)];
      if (whereClause) {
        rows = this.applyWhere(rows, whereClause, params);
      }
      if (orderCol) {
        rows.sort((a, b) => {
          const va = String(a[orderCol] ?? '');
          const vb = String(b[orderCol] ?? '');
          return orderDir === 'DESC' ? vb.localeCompare(va) : va.localeCompare(vb);
        });
      }
      return rows as T[];
    }

    return [];
  }

  private applyWhere(
    rows: Record<string, unknown>[],
    whereClause: string,
    params: unknown[],
  ): Record<string, unknown>[] {
    const conditions = whereClause.split(/\s+AND\s+/i);
    return rows.filter((row) => {
      let paramIdx = 0;
      return conditions.every((cond) => {
        const m = cond.match(/(\w+)\s*(<=|>=|<|>|=|!=)\s*(\?|\d+|'[^']*'|NULL)/i);
        if (!m) return true;

        const [, col, op, rawVal] = m;
        let cmpVal: unknown;
        if (rawVal === '?') {
          cmpVal = params[paramIdx++];
        } else if (rawVal.toUpperCase() === 'NULL') {
          cmpVal = null;
        } else if (/^-?\d+$/.test(rawVal)) {
          cmpVal = Number(rawVal);
        } else {
          cmpVal = rawVal.replace(/^['"]|['"]$/g, '');
        }

        const rowVal = row[col.toLowerCase()];
        const a = String(rowVal ?? '');
        const b = String(cmpVal ?? '');

        switch (op) {
          case '=':
            return a === b;
          case '!=':
            return a !== b;
          case '<=':
            return a <= b;
          case '>=':
            return a >= b;
          case '<':
            return a < b;
          case '>':
            return a > b;
          default:
            return true;
        }
      });
    });
  }

  async getVersion(): Promise<number> {
    return this.version;
  }

  async setVersion(v: number): Promise<void> {
    this.version = v;
  }
}

// ---------------------------------------------------------------------------
// Native Executor — wraps @capacitor-community/sqlite for device builds.
// ---------------------------------------------------------------------------

class NativeExecutor implements DbExecutor {
  private sqlitePromise: Promise<typeof import('@capacitor-community/sqlite')> | null = null;

  constructor(private dbName: string) {}

  private async sqlite() {
    if (!this.sqlitePromise) {
      this.sqlitePromise = import('@capacitor-community/sqlite');
    }
    return this.sqlitePromise;
  }

  async execute(sql: string, params?: unknown[]): Promise<void> {
    const { CapacitorSQLite } = await this.sqlite();
    if (params && params.length > 0) {
      await CapacitorSQLite.run({
        database: this.dbName,
        statement: sql,
        values: params,
      });
    } else {
      await CapacitorSQLite.execute({
        database: this.dbName,
        statements: sql,
      });
    }
  }

  async query<T>(sql: string, params?: unknown[]): Promise<T[]> {
    const { CapacitorSQLite } = await this.sqlite();
    const result = await CapacitorSQLite.query({
      database: this.dbName,
      statement: sql,
      values: params ?? [],
    });
    return (result.values ?? []) as T[];
  }

  async getVersion(): Promise<number> {
    const { CapacitorSQLite } = await this.sqlite();
    const result = await CapacitorSQLite.query({
      database: this.dbName,
      statement: 'PRAGMA user_version',
      values: [],
    });
    const row = result.values?.[0] as Record<string, unknown> | undefined;
    return (row?.user_version as number) ?? 0;
  }

  async setVersion(v: number): Promise<void> {
    const { CapacitorSQLite } = await this.sqlite();
    await CapacitorSQLite.execute({
      database: this.dbName,
      statements: `PRAGMA user_version = ${v}`,
    });
  }
}

// ---------------------------------------------------------------------------
// Public helpers
// ---------------------------------------------------------------------------

let executor: DbExecutor | null = null;
let initPromise: Promise<DbExecutor> | null = null;

export function isNativePlatform(): boolean {
  return Capacitor.isNativePlatform();
}

/** Returns the active executor. Creates a MemoryExecutor lazily if none set yet. */
export function getExecutor(): DbExecutor {
  if (!executor) executor = new MemoryExecutor();
  return executor;
}

function splitStatements(sql: string): string[] {
  return sql
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean);
}

/**
 * Initializes the database:
 * - On native: creates a NativeExecutor via @capacitor-community/sqlite.
 * - On web: falls back to a MemoryExecutor.
 *
 * Migrations are idempotent (CREATE IF NOT EXISTS) and never destroy data.
 */
export async function initDatabase(): Promise<DbExecutor> {
  if (initPromise) return initPromise;

  initPromise = (async () => {
    if (isNativePlatform()) {
      const { CapacitorSQLite } = await import('@capacitor-community/sqlite');
      const dbName = appConfig.databaseName;

      await CapacitorSQLite.createConnection({
        database: dbName,
        version: appConfig.databaseVersion,
        encrypted: false,
        mode: 'no-encryption',
      });
      await CapacitorSQLite.open({ database: dbName });

      executor = new NativeExecutor(dbName);
    } else {
      if (!executor) executor = new MemoryExecutor();
    }

    // Apply pending migrations
    const current = await executor.getVersion();
    for (const m of MIGRATIONS) {
      if (m.version > current) {
        for (const stmt of splitStatements(m.sql)) {
          await executor.execute(stmt, []);
        }
        await executor.setVersion(m.version);
      }
    }

    return executor;
  })();

  return initPromise;
}

/** Resets internal state — intended for tests only. */
export function __resetDatabaseForTests(): void {
  executor = null;
  initPromise = null;
}

export { LATEST_DB_VERSION };
